#pragma once

#include <devioctl.h>

#define RC003_FILTER_API_VERSION 1U
#define RC003_FILTER_MAGIC 0x43524656U
#define RC003_FILTER_SCAN_CODE_COUNT 256U
#define RC003_FILTER_EVENT_CAPACITY 128U
#define RC003_FILTER_HEARTBEAT_TIMEOUT_100NS (2ULL * 1000ULL * 1000ULL * 10ULL)

#define RC003_FILTER_DEVICE_TYPE 0x8000U
#define RC003_FILTER_IOCTL_BASE 0x900U

#define IOCTL_RC003_FILTER_GET_INFO \
    CTL_CODE(RC003_FILTER_DEVICE_TYPE, RC003_FILTER_IOCTL_BASE + 0U, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RC003_FILTER_SET_POLICY \
    CTL_CODE(RC003_FILTER_DEVICE_TYPE, RC003_FILTER_IOCTL_BASE + 1U, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_RC003_FILTER_HEARTBEAT \
    CTL_CODE(RC003_FILTER_DEVICE_TYPE, RC003_FILTER_IOCTL_BASE + 2U, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_RC003_FILTER_READ_EVENTS \
    CTL_CODE(RC003_FILTER_DEVICE_TYPE, RC003_FILTER_IOCTL_BASE + 3U, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_RC003_FILTER_DISARM \
    CTL_CODE(RC003_FILTER_DEVICE_TYPE, RC003_FILTER_IOCTL_BASE + 4U, METHOD_BUFFERED, FILE_WRITE_DATA)

#pragma pack(push, 1)

typedef struct _RC003_FILTER_INFO {
    UINT32 Magic;
    UINT32 ApiVersion;
    UINT32 StructureSize;
    UINT32 AttachedDeviceCount;
    UINT32 PolicyArmed;
    UINT32 QueueDepth;
    UINT64 LastSequence;
    UINT64 DroppedEventCount;
} RC003_FILTER_INFO, *PRC003_FILTER_INFO;

typedef struct _RC003_FILTER_POLICY {
    UINT32 Magic;
    UINT32 ApiVersion;
    UINT32 StructureSize;
    UINT32 Enabled;
    UINT8 SuppressScanCode[RC003_FILTER_SCAN_CODE_COUNT];
} RC003_FILTER_POLICY, *PRC003_FILTER_POLICY;

typedef struct _RC003_FILTER_EVENT {
    UINT32 Magic;
    UINT32 StructureSize;
    UINT64 Sequence;
    UINT64 InterruptTime100ns;
    UINT16 MakeCode;
    UINT16 Flags;
    UINT16 UnitId;
    UINT16 Reserved;
} RC003_FILTER_EVENT, *PRC003_FILTER_EVENT;

typedef struct _RC003_FILTER_EVENT_BATCH {
    UINT32 Magic;
    UINT32 ApiVersion;
    UINT32 StructureSize;
    UINT32 EventCount;
    UINT64 DroppedEventCount;
    RC003_FILTER_EVENT Events[1];
} RC003_FILTER_EVENT_BATCH, *PRC003_FILTER_EVENT_BATCH;

#pragma pack(pop)
